### PR TITLE
Declare Atom namespace and add self atom:link

### PR DESCRIPTION
**Pull request by rjc**
As per RSS Profile recommendation[0], declare Atom namespace, and add `rel="self"` `atom:link` element.

[0] http://www.rssboard.org/rss-profile#namespace-elements-atom

### CODE REVIEW

**Comment by rjc** [comment]
Could you have a look at getting this in, please?

**Comment by rjc** [comment]
Ping.

**Comment by amsehili** [comment]
Hello,
Thanks for your contribution. Sorry for the delay, I've been muting Github notification emails for a while.

**Comment by rjc** [comment]
No worries at all! And thanks for the addition! :^)

**Pull request merged**
