### PR TITLE
Also generate <enclosure> when the file is an image

### PR DESCRIPTION
**Pull request by dzamo**

### CODE REVIEW

**Comment by amsehili** [comment]
I wonder in which use case you'd generate a feed entry with just an image (no audio or video file). In other words, if the enclosure is an image and not an audio/video file then what's the purpose of the entry? (this would be useful for feeds with links to blogs or newspapers articles but this scripts mainly deals with media files).

**Comment by dzamo** [comment]
For me it's useful produce a photo feed from a directory of images which I consider to be one more kind of medial file.  RSS v2 specifies that any standard MIME type is allowed in enclosures so there's no standards-compliance problem and the two feed readers I've tried understand what to do with the image enclosures, so it seems like all benefit to me.  It could be hidden behind a command line flag like `--extended-enclosure-mime-types` to protect users from it, but personally I would only take that measure if this were a deviation from the RSS standard.

**Comment by amsehili** [comment]
Agree that any valid media file should be ok as an enclosure but I still don't see a relevant use case with this script in particular.

If you put an image in the **`enclosure`** tag instead of an audio/video file then you'd just have a feed entry that's useless, unless you manually edit the **`link`** tag and make it point to some web page (e.g., a blog article).

If you don't edit the feed, everything in the **`item`** will point to, say, `myimage.png` which is not very interesting.


Maybe I'm missing a point here, could you please elaborate more on your use case?

```xml
<item>
         <guid>http://localhost:8080/test/media/1.mp3</guid>
         <link>http://localhost:8080/test/media/1.mp3</link>
         <title>1.mp3</title>
         <description>1.mp3</description>
         <pubDate>Sat, 08 Apr 2017 21:19:52 +0000</pubDate>
         <enclosure url="http://localhost:8080/test/media/1.mp3" type="audio/mpeg" length="0"/>
</item>
```

**Comment by dzamo** [comment]
Just putting an image in the enclosure produces a feed of photos, not unlike those I expect people browse at Flickr or Instgram.  I'm not writing blog posts or recording podcasts, just sharing a directory of photos on my server in a subscribable way.  I chose RSS and your script was the easiest way I found to create the feed once I made this one-line edit.

**Comment by amsehili** [comment]
Alright, never thought of such a use case ;)

closes #25.

**Comment by KAMiKAZOW** [comment]
>It could be hidden behind a command line flag like `--extended-enclosure-mime-types` to protect users from it

I think that's a sensible approach because there may be scans of covers in case someone wants to turn their archived audio books into a podcast feed.

**Comment by amsehili** [comment]
Even before this was merged, scanning a directory that contains images and other kinds of files would generate entries for these files, which is something we most certainly don't want. This can be avoided using the `-e` option (explicitly specify desired file extensions).

So the bottom line is, images can either be completely avoided (using `-e` or making sure the directory contains no images), or intentionally included, in which case this MR makes sure they have an enclosure. Using a `--extended-enclosure-mime-types` option means you also want to have images as feed items but you don't want an enclosure sub-element for those items.

**Pull request merged**
