### PR TITLE
Pip installable

### PR DESCRIPTION
**Pull request by maphew**
This PR is pointed at addressing #37. On a Win10 machine with python 3.9.5 this works:

```
git clone https://github.com/maphew/genRSS.git
cd genRSS
pip install --editable .

genRSS -d test/media -e mp3 -t "My Podcast" -p "My Podcast Description" -o feed.rss
```
Resultant [feed.rss](https://github.com/amsehili/genRSS/files/12566547/feed.rss.txt).

This was achieved by: 

a) using a Pyproject.toml skeleton (semi-built by chatgpt-4), 
b) moving to "src layout" packaging scheme, and
c) making genRSS a script that can be run as `genRSS` from anywhere.

Some work remains to make it a good citizen, for instance it's missing readme, keywords, classifiers, etc. ([ref](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)).

### CODE REVIEW

**Review by amsehili — APPROVED** [review]

**Comment by amsehili** [comment]
Great, thanks for your contribution!

**Comment by amsehili** [comment]
Closes #37

**Comment by maphew** [comment]
Happy to help! Thanks for giving me something to start with. I was not looking forward to figuring out how to build podcast rss from the ground up. :-)

**Comment by KAMiKAZOW** [comment]
> Closes #37

You didn't close #37

**Comment by amsehili** [comment]
@KAMiKAZOW thanks, it should have been closed automatically.

**Pull request merged**
