### PR TITLE
Optionally use ID3 tags to populate title and date

### LINKED ISSUE #13: Read MP3 ID3 tags
This could give richer descriptions and dates than the filesystem.

### PR DESCRIPTION
**Pull request by gaul**
Fixes #13.

### CODE REVIEW

**Comment by KAMiKAZOW** [comment]
Not sure if you saw them but https://github.com/cpmpercussion/genRSS/commits/python3 and https://github.com/mronkain/genRSS/commits/master also tackled ID3 reading. Maybe something useful is there.

**Comment by gaul** [comment]
Thanks for the pointer!  Something seems strange about the merge in #10 since this is in the git history but not in the master branch.  It would be nice to unify the functionality from my PR and the two other branches.  @cpmpercussion @mronkain

**Comment by KAMiKAZOW** [comment]
@gaul I used the Python 3 porting work by @cpmpercussion, changed the xrange thing and opened the PR. @amsehili apparently wasn't interested in forced ID3 usage (and iTunes Tags) and removed those bits again. That's why the commit is in the history but did not end up in Master.

Not a programmer myself, so I couldn't do much except rudimentary stuff like xrage, copyright dates, and alike.

**Comment by amsehili** [comment]
Definitely a good feature, I'll have a look at this asap.

Ideally the script falls back to the default behavior if a dependency (mutagen) is not installed. The tests should also be updated.

**Pull request closed without merging**
