### PR TITLE
Generate default title via user name

### PR DESCRIPTION
**Pull request by gaul**

### CODE REVIEW

**Comment by amsehili** [comment]
`getpass.getuser()` returns login name an not actual user name.
Not sure that this default would suit everybody.

**Comment by KAMiKAZOW** [comment]
What's even the benefit of this? If the default title string being empty is bad (triggering bugs in podcast players or whatever), why not just "Untitled Podcast" or the folder's name?

If anyone released that podcast feed, leaking the user name just by accidentally not specifying a title sounds like a privacy issue to me.

**Comment by gaul** [comment]
The default is something likely to be recognizable to users, e.g., "gaul's feed".  Users can override it if they don't like it.  I don't know what the difference between a login name and user name is but these are the same on my system.

I'm not sure how leaking a user name is a privacy issue since most services have some concept of user names.  Also the primary use case for this software is a private feed served via localhost.

**Comment by KAMiKAZOW** [comment]
> The default is something likely to be recognizable to users, e.g., "gaul's feed"

IMO chances are higher that the folder name the MP3s sit in is more useful as default, eg.  recordings of courses in university would likely sit in a folder named after that course, no?

**Comment by amsehili** [comment]
@gaul user name can be your full name which may include spaces. When installing Ubuntu for example you have the possibility to set both. It's also the name MS Office uses to set the author in document metadata.

The downside of using user name as the default title is that many feeds will have the same title unless you remember to edit each one after generation. Using folder name seems more interesting. 

One can also make this parameter mandatory and force the use to set it explicitly.

**Pull request closed without merging**
